// Updated realistic catalog data (12 products across 4 categories)
// Includes id, name, price, category, shortDescription, longDescription, image, sku, stock
// Also provides properties expected by app.js: description, rating, imageAlt

const products = [
  // Shoes
  {
    id: 1,
    name: "Runner Pro Sneakers",
    category: "shoes",
    price: 89.99,
    rating: 4.6,
    stock: 28,
    sku: "SKU-SHOE-0001",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
    imageAlt: "Lightweight grey running sneakers on a minimal background",
    shortDescription: "Breathable daily trainers for comfort and performance.",
    longDescription: "Engineered mesh upper keeps you cool, responsive midsole cushions every step, and grippy outsole ensures traction on city streets and light trails.",
    description: "Engineered mesh upper with responsive cushioning for all-day comfort.",
  },
  {
    id: 2,
    name: "City Walker Boots",
    category: "shoes",
    price: 129.0,
    rating: 4.5,
    stock: 16,
    sku: "SKU-SHOE-0002",
    image: "https://images.pexels.com/photos/1032110/pexels-photo-1032110.jpeg",
    imageAlt: "Brown leather boots standing upright on a wooden surface",
    shortDescription: "Durable leather boots with cushioned insoles.",
    longDescription: "Full-grain leather, stitched welt, and a shock-absorbing midsole make these boots a dependable companion from commute to weekend escapes.",
    description: "Full-grain leather boots with cushioned insoles for day-long comfort.",
  },
  {
    id: 3,
    name: "Ultralight Trainers",
    category: "shoes",
    price: 74.5,
    rating: 4.3,
    stock: 34,
    sku: "SKU-SHOE-0003",
    image: "https://picsum.photos/id/21/800/600",
    imageAlt: "Minimal white trainers against a soft backdrop",
    shortDescription: "Featherlight trainers with responsive cushioning.",
    longDescription: "A flexible knit upper pairs with a featherlight foam midsole to deliver effortless movement and comfort on the go.",
    description: "Flexible knit upper and featherlight foam for effortless movement.",
  },

  // Apparel
  {
    id: 4,
    name: "Everyday Tee",
    category: "apparel",
    price: 24.5,
    rating: 4.4,
    stock: 120,
    sku: "SKU-APP-1001",
    image: "https://images.pexels.com/photos/1261422/pexels-photo-1261422.jpeg",
    imageAlt: "Folded cotton t-shirt on a table",
    shortDescription: "Soft, breathable cotton tee with a clean silhouette.",
    longDescription: "100% combed cotton with a tailored fit, reinforced collar, and pre-shrunk fabric for a durable, everyday essential.",
    description: "Soft, breathable cotton tee with a clean silhouette and tailored fit.",
  },
  {
    id: 5,
    name: "Minimal Hoodie",
    category: "apparel",
    price: 59.0,
    rating: 4.3,
    stock: 72,
    sku: "SKU-APP-1002",
    image: "https://picsum.photos/id/1062/800/600",
    imageAlt: "Light grey hoodie neatly folded on a bench",
    shortDescription: "Cozy fleece-lined hoodie with a minimalist design.",
    longDescription: "Midweight fleece with a brushed interior, roomy kangaroo pocket, and ribbed cuffs for a warm, timeless layer.",
    description: "Cozy fleece-lined hoodie with a minimalist design and roomy pocket.",
  },
  {
    id: 6,
    name: "Tech Performance Jacket",
    category: "apparel",
    price: 119.0,
    rating: 4.5,
    stock: 26,
    sku: "SKU-APP-1003",
    image: "https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg",
    imageAlt: "Black technical jacket hanging on a hook",
    shortDescription: "Water-resistant, windproof jacket with breathable lining.",
    longDescription: "Sealed seams, storm flap, and breathable membrane deliver weather protection without bulk—ideal for city and trail.",
    description: "Water-resistant, windproof jacket with breathable lining for any weather.",
  },

  // Electronics
  {
    id: 7,
    name: "Noise-Cancel Headphones",
    category: "electronics",
    price: 159.0,
    rating: 4.7,
    stock: 20,
    sku: "SKU-ELC-2001",
    image: "https://images.pexels.com/photos/3825572/pexels-photo-3825572.jpeg",
    imageAlt: "Over-ear wireless headphones on a desk",
    shortDescription: "Immersive sound with active noise cancellation.",
    longDescription: "30-hour battery, multi-point Bluetooth pairing, and studio-tuned drivers let you focus on the music anywhere.",
    description: "Immersive sound with active noise cancellation and 30-hour battery life.",
  },
  {
    id: 8,
    name: "Compact Bluetooth Speaker",
    category: "electronics",
    price: 49.0,
    rating: 4.4,
    stock: 48,
    sku: "SKU-ELC-2002",
    image: "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg",
    imageAlt: "Portable speaker on a coffee table",
    shortDescription: "Portable speaker with rich bass and splash resistance.",
    longDescription: "Pocket-sized with a passive radiator for bass, IPX5 splash resistance, and a 12-hour battery for daily tunes.",
    description: "Portable speaker with rich bass and splash-resistant build.",
  },
  {
    id: 9,
    name: "Smart Fitness Watch",
    category: "electronics",
    price: 199.99,
    rating: 4.2,
    stock: 30,
    sku: "SKU-ELC-2003",
    image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
    imageAlt: "Black fitness smartwatch displaying steps",
    shortDescription: "Track workouts, heart rate, sleep, and notifications.",
    longDescription: "24/7 heart-rate monitoring, GPS, water resistance to 50m, and a bright AMOLED screen for clear stats.",
    description: "Track workouts, heart rate, sleep, and notifications with style.",
  },

  // Accessories
  {
    id: 10,
    name: "Explorer Daypack",
    category: "accessories",
    price: 79.0,
    rating: 4.5,
    stock: 42,
    sku: "SKU-ACC-3001",
    image: "https://picsum.photos/id/1068/800/600",
    imageAlt: "Minimal daypack leaning against a wall",
    shortDescription: "Streamlined 20L daypack for work and weekend trips.",
    longDescription: "Durable water-repellent fabric, padded laptop sleeve, and quick-access top pocket keep essentials organized on the go.",
    description: "Durable 20L daypack with padded laptop sleeve and quick-access pocket.",
  },
  {
    id: 11,
    name: "Classic Sunglasses",
    category: "accessories",
    price: 39.0,
    rating: 4.1,
    stock: 85,
    sku: "SKU-ACC-3002",
    image: "https://picsum.photos/id/433/800/600",
    imageAlt: "Black classic sunglasses on a table",
    shortDescription: "UV400 polarized shades with timeless styling.",
    longDescription: "Polarized lenses reduce glare while the lightweight acetate frame offers day-long comfort in a classic profile.",
    description: "Polarized UV400 sunglasses with lightweight acetate frame.",
  },
  {
    id: 12,
    name: "Leather Belt",
    category: "accessories",
    price: 34.0,
    rating: 4.2,
    stock: 60,
    sku: "SKU-ACC-3003",
    image: "https://picsum.photos/id/1080/800/600",
    imageAlt: "Brown leather belt coiled neatly",
    shortDescription: "Full-grain leather belt with matte buckle.",
    longDescription: "Hand-finished belt cut from full-grain leather with sturdy stitching and a matte-finish buckle for daily wear.",
    description: "Full-grain leather belt with durable stitching and matte buckle.",
  },
];

// Expose for non-module scripts
window.products = products;
