// /scripts/products.js

const products = [
  {
    id: 1,
    name: "Running Shoes",
    category: "Shoes",
    price: 79.99,
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Lightweight and comfortable running shoes, perfect for your daily jog.",
  },
  {
    id: 2,
    name: "Leather Boots",
    category: "Shoes",
    price: 149.99,
    image: "https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Durable and stylish leather boots for any occasion.",
  },
  {
    id: 3,
    name: "Cotton T-Shirt",
    category: "Apparel",
    price: 24.99,
    image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "A classic, soft cotton t-shirt available in various colors.",
  },
  {
    id: 4,
    name: "Denim Jacket",
    category: "Apparel",
    price: 89.99,
    image: "https://images.pexels.com/photos/161709/new-york-usa-street-style-161709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "A timeless denim jacket that completes any casual look.",
  },
  {
    id: 5,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 199.99,
    image: "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "High-fidelity wireless headphones with noise-cancellation.",
  },
  {
    id: 6,
    name: "Smartwatch",
    category: "Electronics",
    price: 249.99,
    image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Stay connected and track your fitness with this modern smartwatch.",
  },
  {
    id: 7,
    name: "Classic Sneakers",
    category: "Shoes",
    price: 65.00,
    image: "https://images.pexels.com/photos/2421374/pexels-photo-2421374.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Versatile and comfortable sneakers for everyday wear.",
  },
  {
    id: 8,
    name: "Hoodie",
    category: "Apparel",
    price: 55.00,
    image: "https://images.pexels.com/photos/7129693/pexels-photo-7129693.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "A warm and cozy hoodie, perfect for cooler weather.",
  },
  {
    id: 9,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 45.50,
    image: "https://images.pexels.com/photos/1279813/pexels-photo-1279813.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Portable Bluetooth speaker with rich, powerful sound.",
  },
  {
    id: 10,
    name: "Leather Wallet",
    category: "Accessories",
    price: 39.99,
    image: "https://images.pexels.com/photos/983297/pexels-photo-983297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "A sleek and durable leather wallet with multiple compartments.",
  }
];
